name = "Whack-A-Ninja"

[store]
id="com.github.M4ss1ck.whackANinja"
version_name=1.0
version_code=3
author="M4ss1ck"
author_email="massick@systemli.org"
description="Whack-A-Mole clon. Click on the ninja to get points"